// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for macos - '
            'support for macos is coming soon and will be configured automatically.');
      case TargetPlatform.windows:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for windows - '
            'support for windows is coming soon and will be configured automatically.');
      case TargetPlatform.linux:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'support for linux is coming soon and will be configured automatically.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtXcXweUemCk60mShfiVVyRC4Efj_NKBo',
    appId: '1:1068542407878:web:5465df458acca428ab13c7',
    messagingSenderId: '1068542407878',
    projectId: 'invtrack-app-835921',
    authDomain: 'invtrack-app-835921.firebaseapp.com',
    storageBucket: 'invtrack-app-835921.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtXcXweUemCk60mShfiVVyRC4Efj_NKBo',
    appId: '1:1068542407878:android:cdd45d77a32bd693ab13c7',
    messagingSenderId: '1068542407878',
    projectId: 'invtrack-app-835921',
    storageBucket: 'invtrack-app-835921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtXcXweUemCk60mShfiVVyRC4Efj_NKBo',
    appId: '1:1068542407878:ios:be23b754e3860431ab13c7',
    messagingSenderId: '1068542407878',
    projectId: 'invtrack-app-835921',
    storageBucket: 'invtrack-app-835921.appspot.com',
    iosClientId:
        '1068542407878-kucqjrqnh3a22jmh904s6t9cll2ag3t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.invtrack',
  );
}
